#pragma once

#include "Arduino.h"
#include "ESP8266WiFi.h"
#include "ESP8266WebServer.h"
#include "WiFiUdp.h"
#include "FS.h"
#include "SoftwareSerial.h"
#include "ArduinoJson.h"

#include "..\..\..\shared\headers\Const.h"
#include "..\..\..\shared\headers\Unions.h"
#include "..\..\..\shared\headers\CarStateMessage.h"
#include "..\..\..\shared\headers\SerialSerializer.h"
#include "..\..\..\shared\headers\RemoteCarState.h"
#include "..\..\..\shared\headers\RemoteCarStateSerializer.h"
#include "..\..\..\shared\headers\Logger.h"

#include "headers\CarState.h"
#include "headers\CarSettings.h"
#include "headers\CarSettingsJsonSerializer.h"
#include "headers\StateOwner.h"
#include "headers\SerialTransmitter.h"
#include "headers\MessageDispatcher.h"
#include "headers\FileSystem.h"
#include "headers\WiFiAccessPoint.h"
#include "headers\HttpAdapter.h"
#include "headers\UdpAdapter.h"